// This is an autogenerated file, DO NOT EDIT.
// This file was generated from `blackboard.ts` by executing the `codegen.ts` file.
import type { IBlackboardObject, IBlackboard } from '../ai/blackboard';

export function CastToBlackboardObject(obj: any): IBlackboardObject | null {
  return obj !== null && obj !== undefined ? obj : null;
}

export function CastToBlackboard(obj: any): IBlackboard | null {
  return obj !== null &&
    obj !== undefined &&
    typeof obj.set === 'function' &&
    typeof obj.get === 'function' &&
    typeof obj.tagObject === 'function' &&
    typeof obj.removeObjectTags === 'function' &&
    typeof obj.getTagged === 'function'
    ? obj
    : null;
}
