// This is an autogenerated file, DO NOT EDIT.
// This file was generated from `QuadTree.ts` by executing the `codegen.ts` file.
import type { IQuadTree } from '../data-structures/QuadTree';
import { Rect } from './Rect';

export function CastToQuadTree<T extends Rect>(obj: any): IQuadTree<T> | null {
  return obj !== null &&
    obj !== undefined &&
    typeof obj.getAllObjects === 'function' &&
    typeof obj.clear === 'function' &&
    typeof obj.insert === 'function' &&
    typeof obj.getAt === 'function' &&
    typeof obj.query === 'function' &&
    typeof obj.intersect === 'function' &&
    typeof obj.getHeight === 'function' &&
    typeof obj.getWidth === 'function'
    ? obj
    : null;
}
