// This is an autogenerated file, DO NOT EDIT.
// This file was generated from `NavMeshCongestionService.ts` by executing the `codegen.ts` file.
import type { INavMeshCongestionService } from '../navmesh/NavMeshCongestionService';

export function CastToNavMeshCongestionService(
  obj: any
): INavMeshCongestionService | null {
  return obj !== null &&
    obj !== undefined &&
    typeof obj.initializeService === 'function' &&
    typeof obj.onServicesReady === 'function' &&
    typeof obj.setCongestionLine === 'function' &&
    typeof obj.addCongestionAt === 'function' &&
    typeof obj.update === 'function' &&
    typeof obj.getCongestionAt === 'function' &&
    typeof obj.sampleCongestionAlongLine === 'function' &&
    typeof obj.addHeatSource === 'function'
    ? obj
    : null;
}
