// This is an autogenerated file, DO NOT EDIT.
// This file was generated from `LuaVM.ts` by executing the `codegen.ts` file.
import type { ILuaVM } from '../lua/LuaVM';

export function CastToLuaVM(obj: any): ILuaVM | null {
  return obj !== null &&
    obj !== undefined &&
    typeof obj.execute === 'function' &&
    typeof obj.callFunction === 'function' &&
    typeof obj.registerHook === 'function' &&
    typeof obj.unregisterHook === 'function' &&
    typeof obj.getGlobal === 'function' &&
    typeof obj.dispose === 'function'
    ? obj
    : null;
}
