// This is an autogenerated file, DO NOT EDIT.
// This file was generated from `Coroutines.ts` by executing the `codegen.ts` file.
import type { ICoroutine, ICoroutineService } from "../utils/Coroutines";

export function CastToCoroutine<T>(obj: any): ICoroutine<T> | null {
  return obj !== null &&
    obj !== undefined &&
    typeof obj.run === "function" &&
    typeof obj.reset === "function" &&
    typeof obj.stop === "function" &&
    typeof obj.stopped === "boolean" &&
    typeof obj.complete === "boolean"
    ? obj
    : null;
}

export function CastToCoroutineService(obj: any): ICoroutineService | null {
  return obj !== null &&
    obj !== undefined &&
    typeof obj.start === "function" &&
    typeof obj.stop === "function" &&
    typeof obj.add === "function" &&
    typeof obj.remove === "function" &&
    typeof obj.make === "function"
    ? obj
    : null;
}
