// This is an autogenerated file, DO NOT EDIT.
// This file was generated from `Dispatcher.ts` by executing the `codegen.ts` file.
import type { IDispatcher } from '../utils/Dispatcher';

export function CastToDispatcher<T>(obj: any): IDispatcher<T> | null {
  return (obj !== null && obj !== undefined && typeof(obj.subscribe) === "function" && typeof(obj.unsubscribe) === "function" && typeof(obj.dispatch) === "function") ? obj : null;
}
