// This is an autogenerated file, DO NOT EDIT.
// This file was generated from `ObjectPool.ts` by executing the `codegen.ts` file.
import type { IObjectPool } from "../utils/ObjectPool";

export function CastToObjectPool<T>(obj: any): IObjectPool<T> | null {
  return obj !== null &&
    obj !== undefined &&
    typeof obj.seed === "function" &&
    typeof obj.get === "function" &&
    typeof obj.put === "function"
    ? obj
    : null;
}
