// This is an autogenerated file, DO NOT EDIT.
// This file was generated from `Voxelizer.ts` by executing the `codegen.ts` file.
import type { IVoxel } from "../utils/Voxelizer";

export function CastToVoxel(obj: any): IVoxel | null {
  return obj !== null &&
    obj !== undefined &&
    typeof obj.x === "number" &&
    typeof obj.y === "number" &&
    typeof obj.width === "number" &&
    typeof obj.height === "number"
    ? obj
    : null;
}
