// This is an autogenerated file, DO NOT EDIT.
// This file was generated from `ZOrderCurve.ts` by executing the `codegen.ts` file.
import type { ICurve2D } from '../utils/ZOrderCurve';

export function CastToCurve2D(obj: any): ICurve2D | null {
  return (obj !== null && obj !== undefined && typeof(obj.getIndex) === "function" && typeof(obj.getXY) === "function") ? obj : null;
}
