// This is an autogenerated file, DO NOT EDIT.
// This file was generated from `Triggers.ts` by executing the `codegen.ts` file.
import type { ITriggerService, ITrigger } from '../phaser/Triggers';

export function CastToTriggerService(obj: any): ITriggerService | null {
  return obj !== null &&
    obj !== undefined &&
    typeof obj.initializeService === 'function' &&
    typeof obj.onServicesReady === 'function' &&
    typeof obj.registerTrigger === 'function' &&
    typeof obj.update === 'function'
    ? obj
    : null;
}

export function CastToTrigger(obj: any): ITrigger | null {
  return obj !== null &&
    obj !== undefined &&
    typeof obj.getRadius === 'function' &&
    typeof obj.getPosition === 'function' &&
    typeof obj.handleTriggerEnter === 'function' &&
    typeof obj.handleTriggerExit === 'function'
    ? obj
    : null;
}
