// This is an autogenerated file, DO NOT EDIT.
// This file was generated from `RVOManager.ts` by executing the `codegen.ts` file.
import type { IRVOService, IRVOAgent } from "../rvo/RVOManager";

export function CastToRVOService(obj: any): IRVOService | null {
  return obj !== null &&
    obj !== undefined &&
    typeof obj.initializeService === "function" &&
    typeof obj.onServicesReady === "function" &&
    typeof obj.registerAgent === "function" &&
    typeof obj.clearObstacles === "function" &&
    typeof obj.registerSingleObstacle === "function" &&
    typeof obj.registerObstacles === "function" &&
    typeof obj.moveObstacle === "function" &&
    typeof obj.getObstacle === "function" &&
    typeof obj.getAllObstacles === "function"
    ? obj
    : null;
}

export function CastToRVOAgent(obj: any): IRVOAgent | null {
  return obj !== null &&
    obj !== undefined &&
    typeof obj.update === "function" &&
    typeof obj.getPreferredVelocity === "function" &&
    typeof obj.x === "number" &&
    typeof obj.y === "number"
    ? obj
    : null;
}
