// This is an autogenerated file, DO NOT EDIT.
// This file was generated from `LLMProviderService.ts` by executing the `codegen.ts` file.
import type { ILLMProviderService } from '../services/LLMProviderService';

export function CastToLLMProviderService(obj: any): ILLMProviderService | null {
  return obj !== null && obj !== undefined && typeof obj.send === 'function'
    ? obj
    : null;
}
