// This is an autogenerated file, DO NOT EDIT.
// This file was generated from `ISpring.ts` by executing the `codegen.ts` file.
import type { ISpring } from '../springs/ISpring';

export function CastToSpring<TValue>(obj: any): ISpring<TValue> | null {
  return obj !== null &&
    obj !== undefined &&
    typeof obj.update === 'function' &&
    typeof obj.setGoal === 'function' &&
    typeof obj.setValue === 'function' &&
    typeof obj.predict === 'function' &&
    typeof obj.Value !== 'undefined' &&
    typeof obj.GoalValue !== 'undefined' &&
    typeof obj.GoalVelocity !== 'undefined' &&
    typeof obj.Velocity !== 'undefined'
    ? obj
    : null;
}
