// This is an autogenerated file, DO NOT EDIT.
// This file was generated from `PhoenixChannelService.ts` by executing the `codegen.ts` file.
import type { IPhoenixChannel, IPhoenixChannelService } from '../services/PhoenixChannelService';

export function CastToPhoenixChannel(obj: any): IPhoenixChannel | null {
  return (obj !== null && obj !== undefined && typeof(obj.sendRPC) === "function" && typeof(obj.subscribe) === "function") ? obj : null;
}

export function CastToPhoenixChannelService(obj: any): IPhoenixChannelService | null {
  return (obj !== null && obj !== undefined && typeof(obj.getChannel) === "function") ? obj : null;
}
