// This is an autogenerated file, DO NOT EDIT.
// This file was generated from `SceneService.ts` by executing the `codegen.ts` file.
import type { ISceneService } from '../services/SceneService';

export function CastToSceneService(obj: any): ISceneService | null {
  return (obj !== null && obj !== undefined && typeof(obj.getScene) === "function" && typeof(obj.getClock) === "function") ? obj : null;
}
