// This is an autogenerated file, DO NOT EDIT.
// This file was generated from `ServiceContainer.ts` by executing the `codegen.ts` file.
import type { IService, IServiceContainer } from '../services/ServiceContainer';

export function CastToService(obj: any): IService | null {
  return (obj !== null && obj !== undefined && typeof(obj.initializeService) === "function" && typeof(obj.onServicesReady) === "function") ? obj : null;
}

export function CastToServiceContainer(obj: any): IServiceContainer | null {
  return (obj !== null && obj !== undefined && typeof(obj.register) === "function" && typeof(obj.getService) === "function" && typeof(obj.tryGetService) === "function") ? obj : null;
}
